<?php
/**
 * Compatibility shims for KSES (content filtering) for WordPress 7.2.
 *
 * @package gutenberg
 */

/**
 * Adds background-clip and its vendor-prefixed companions to the list of safe
 * CSS properties.
 *
 * The {@see safecss_filter_attr()} function only keeps allowlisted CSS
 * properties. Without these entries the declarations generated by the
 * background clip block support are stripped, leaving the style engine with an
 * empty `css` string.
 *
 * @param string[] $attr Array of allowed CSS attributes.
 * @return string[] Modified array of allowed CSS attributes.
 */
function gutenberg_add_background_clip_to_safe_style_css( array $attr ): array {
	$background_clip_properties = array(
		'background-clip',
		'-webkit-background-clip',
		'-webkit-text-fill-color',
	);

	foreach ( $background_clip_properties as $property ) {
		if ( ! in_array( $property, $attr, true ) ) {
			$attr[] = $property;
		}
	}

	return $attr;
}
add_filter( 'safe_style_css', 'gutenberg_add_background_clip_to_safe_style_css' );
